customer-groups:
  # number of generated customer groups
  elementCount: 15
  # range of customers per customer group
  minCustomers: 5
  maxCustomers: 50

  # generate random custom attributes
  generatedAttributes:
    elementCount: 5
