# Configurations for libraries, folders and content assets. CustomAttributes are not supported yet. There is a main
# library defined by "libraryConfig:". This library can contain additional further customized custom libraries under
# "libraries:" and customized folders under "folders:".
# If the library "ComdagenSharedLibrary" exists and contains a content asset named "ComdagenSummary" then this will be
# rendered in a central content slot on the store front.
libraryConfig:
  # root folder for libraries
  outputDir: "libraries"
  # Top level seed
  initialSeed: 1234


  # Total number of generated content assets per library
  generatedContentAssetCount: 30

  # Total number of generated folders per library. Custom specified folders are generated first followed by default
  # generated folders up to "generatedFolderCount" folders
  generatedFolderCount: 10

  # Generates a content asset containing the top level seeds and names of all generated libraries and
  # sites if generateSummaryContentAsset is set to true or is left out in the config. Additionally display
  # product count for sites and content asset count for libraries. This content asset counts towards
  # generatedContentAssetCount meaning, if generateSummaryContentAsset is set to true or is left out in the config,
  # there will be 9 normally generated content assets.
  generateSummaryContentAsset: true


  # This overrides default settings for content asset generation
  contentAssetDefaults:
    # Either use random contentIds or ContentId_<number> when generating random content assets
    useRandomContentIds: true
    classificationFolder: "root"

  # This overrides default settings for folder generation
  folderDefaults:
    onlineFlag: false
    # Use randomly generated folderIds instead of Folder_<index>
    randomFolderIds: false
    # Parent folder
    parent: "root"

  # Creating a custom folder for each entry
#  folders:
#  # If no folderId is given a randomized generated one is being used
#  - folderId: "root"
#    displayName: "Root folder"
#    description: "Offers comdagen generated content"
#    onlineFlag: true
#
#  - folderId: "ComdagenContent"
#    displayName: "Custom comdagen folder"
#    description:  "Content folder for Comdagen generated content"
#    onlineFlag: true
#    parent: "root"
#
#  - folderId: "ComdagenContentAssets"
#    displayName: "Custom comdagen folder"
#    description: "Content folder for Comdagen generated content"
#    onlineFlag: true
#    parent: "ComdagenContent"