shipping:
  # number of generated shipping promotions
  elementCount: 5
  # price range of each shipping promotion
  minPrice: 3.0
  maxPrice: 50.0

  # generate random custom attributes
  generatedAttributes:
    elementCount: 5
